spring.application.name=MyBlog

spring.datasource.url=jdbc:mysql://localhost:3306/db_myblog?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Activer la création ou la mise à jour des tables
spring.jpa.hibernate.ddl-auto=update

# Montrer les logs SQL Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Activer les logs de requêtes SQL au niveau DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Le secret doit contenir au moins 32 caractères
security.jwt.secret-key=${JWT_SECRET_KEY}

#1h in millisecond
security.jwt.expiration-time=3600000
